# Generated by Django 6.1.1 on 2026-09-18 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(choices=[('SEXUAL_VIOLENCE', 'Sexual Violence & Rape'), ('DOMESTIC_ABUSE', 'Domestic / Intimate Partner Violence'), ('PHYSICAL_ASSAULT', 'Physical Assault & Battery'), ('HARASSMENT_STALKING', 'Harassment & Stalking'), ('CHILD_EARLY_MARRIAGE', 'Harmful Practices & Child Exploitation'), ('OTHER', 'Other Unspecified Abuse')], max_length=50)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Standard'), ('HIGH', 'High Priority'), ('CRITICAL', 'Immediate Threat / Medical Emergency')], default='MEDIUM', max_length=20)),
                ('description', models.TextField(help_text='Narrative of the incident (scrubbed of direct PII)')),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('region_state', models.CharField(help_text='e.g., Addis Ababa, Oromia', max_length=100)),
                ('city_district', models.CharField(help_text='e.g., Bole Sub-City, Woreda 03', max_length=100, null=True)),
                ('approximate_location', models.CharField(blank=True, help_text='Optional general landmark or neighborhood (no specific home addresses)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Initial Review'), ('TRIAGED', 'Case Verified & Triaged'), ('ASSIGNED', 'Assigned to Support Organization'), ('ACTION_IN_PROGRESS', 'Protective Action in Progress'), ('RESOLVED', 'Case Resolution / Protective Action Completed')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='reports.incidentreport')),
            ],
        ),
    ]
