# Generated by Django 6.1.1 on 2026-09-18 22:00

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('claim_token', models.CharField(default=reports.models.generate_claim_token, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('SEXUAL_VIOLENCE', 'Sexual Violence & Rape'), ('DOMESTIC_ABUSE', 'Domestic / Intimate Partner Violence'), ('PHYSICAL_ASSAULT', 'Physical Assault'), ('HARASSMENT_STALKING', 'Harassment & Stalking'), ('CHILD_EARLY_MARRIAGE', 'Harmful Practices / Child Exploitation')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRIAGE', 'Case Received & Hash Verified'), ('ASSIGNED', 'Assigned to Legal Aid Clinic'), ('ACTION', 'Emergency Shelter Referral Dispatched'), ('RESOLVED', 'Case Resolution / Legal Action')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='reports.incidentreport')),
            ],
        ),
    ]
