# Generated by Django 6.1.1 on 2026-09-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Initial Review'), ('TRIAGED', 'Case Verified & Triaged'), ('ASSIGNED', 'Assigned to Support Organization'), ('ACTION_IN_PROGRESS', 'Protective Action in Progress'), ('RESOLVED', 'Case Resolution / Protective Action Completed'), ('REFERRED_TO_PARTNER', 'Referred to Partner Organization')], default='PENDING', max_length=30),
        ),
    ]
