# Generated by Django 6.1.1 on 2026-09-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_incidentreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponderOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tier', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=150)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
